### PR TITLE
Add another pass to /about

### PR DESCRIPTION
**Pull request by jessicard**
Last documentation pass was about clarifying how to make a scrapbook, how to run the app locally, and documenting the Scrappy commands. This documentation pass is about how the whole page works together!

Update README and `/about` page to improve clarity, grammar, and hide the larger sections (like the Scrappy commands) behind a toggle.

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/about**](https://scrapbook-93dg2v6m7.hackclub.dev/about) |
|:-:|
|<a href="https://scrapbook-93dg2v6m7.hackclub.dev/about">Screenshot of /about</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/atWZ8o6J15ChXdGPFFM1UhNqgRhkoosWEdQvkZ2NlYY6pmEX7jTXCLlg00VcZD8p0Gj4YD_yJWiTwFA5vDu84A.png">(view full size)</a> |







Commit bd826dba4891a8ba7a110e923e1b6fa3c7196731 (https://scrapbook-93dg2v6m7.hackclub.dev).

**Comment by jessicard** [comment]
Related PR: https://github.com/hackclub/scrappy/pull/317

**Comment by jessicard** [comment]
Ready for review @sampoder ! But lets wait to merge it until https://github.com/hackclub/scrappy/pull/317 is merged, since this PR references that README.

**Review by sampoder — APPROVED** [review]
I'm happy with these, thank you!

**Pull request merged**
