### PR TITLE
feature - added basic search bar to search people on scrapbook!

### PR DESCRIPTION
**Pull request by ShubhamPatilsd**
This PR creates a search bar where users can input the usernames of people they want to find on scrapbook. Very basic and doesn't contain any more profile data other than the username and avatar.

(cc: @sampoder because you asked me to :D )

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/**](https://summer-streaks-lb2yjuhlx.hackclub.dev/) | [**/search**](https://summer-streaks-lb2yjuhlx.hackclub.dev/search) |
|:-:|:-:|
|<a href="https://summer-streaks-lb2yjuhlx.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/30qvYJImitJuzGmTFicYBzSde2XTVIpdRgIupHyYZxImTBNVlgDfYD9szqD0kY_mYDXeOhgm_fUb8BgFf-k1vQ.png">(view full size)</a> |<a href="https://summer-streaks-lb2yjuhlx.hackclub.dev/search">Screenshot of /search</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/UGYxnUvcIsUn-pJJsC7NzHFYgC2qNsQqC4S_9Gas_X61Q-OVa2a6u87Y4eO7sj_Yy_8D7n6rUouNIlhPB3Czhw.png">(view full size)</a> |



And 1 other route:
- [**/api/users/search**](https://summer-streaks-lb2yjuhlx.hackclub.dev/api/users/search)



Commit a5cbce23a575fe843bb08223e094bb11cdad9859 (https://summer-streaks-lb2yjuhlx.hackclub.dev).

**Comment by ShubhamPatilsd** [comment]
I was thinking of doing a popup but I had no clue where to start. Is it just like a re-run of the function call when the textbox content changes?

Also, where is the documentation on how to implement darkmode?

**Comment by ShubhamPatilsd** [comment]
@sampoder i fixed the issues in the updated code!

**Comment by ShubhamPatilsd** [comment]
Oh shoot i just realized how laggy it is when searching for someone oh my goodness. Is there a way to fix this?

**Comment by ShubhamPatilsd** [comment]
Actually what i might do is get a huge amount of data from the backend and render that on the frontend. Right now I'm making a bunch of API calls but I'm thinking that instead of that I would get all the profiles on the frontend and filter through those. That might fail but I'll see how it fares

**Comment by sampoder** [comment]
Sorry, wrong screenshot:
Screenshot 2021-10-24 at 9 35 12 AM

**Comment by ShubhamPatilsd** [comment]
Hmm that's weird. Looks like filtering through the array takes time. Are there faster alternatives?

**Comment by sampoder** [comment]
closing due to merge conflicts, let me know if you'd like to restart this!

**Pull request closed without merging**
