### PR TITLE
make new post button more reachable

### PR DESCRIPTION
**Pull request by JosiasAurel**
places the "New Post" button at the bottom of the page, fixed so it's easily reachable and obvious you can post from the web UI. 
Helps with #536

### CODE REVIEW

**Review by sampoder — CHANGES_REQUESTED** [review]
Would it be possible to make the padding even on all sides?

Screenshot 2023-09-08 at 3 48 42 PM

**Comment by JosiasAurel** [comment]
> Would it be possible to make the padding even on all sides?
> 
> Screenshot 2023-09-08 at 3 48 42 PM

this should be resolved now

**Review by grymmy — APPROVED** [review]
lgtm, suggest @sampoder reviews before landing.

**Review by sampoder — APPROVED** [review]
let's do it!

**Pull request merged**
