### PR TITLE
Add streaks link

### PR DESCRIPTION
**Pull request by J-cordz**
This Pull Request adds a link on the Scrapbook main page to the streaks page.

### CODE REVIEW

**Review by exu3 — APPROVED** [review]
Looks good, thanks for the PR!

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/**](https://scrapbook-i6dj9twje.hackclub.dev/) |
|:-:|
|<a href="https://scrapbook-i6dj9twje.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/RaK96X-n_0OiwBlAcbDEkxVlKGupoIWuOilgcfCVLTO7798DVBRoBrLFDz8fp_z4OZa_OYxl5xyWpLpx7haX1g.png">(view full size)</a> |







Commit 569458e4dc170d4fe376fb0335b2624ee7951d53 (https://scrapbook-i6dj9twje.hackclub.dev).

**Review by sampoder — APPROVED** [review]
Thanks for the PR @J-cordz! 

###### Sneaky way to put in a little bit of a flex ;)

**Comment by J-cordz** [comment]
Thanks @sampoder! I'm happy to help :D

**Pull request merged**
